# default values
all:
  facebook:
    api_key: xxx
    api_secret: xxx
    api_id: xxx
    callback_url: http://www.yourserver.com
    app_url:      http://apps.facebook.com/your-app

  sf_guard_plugin:
    profile_class: sfGuardUserProfile
    profile_field_name: user_id
    profile_facebook_uid_name: facebook_uid
    profile_email_name: email
    profile_email_hash_name: email_hash

  facebook_connect:
    load_routing:     true
    user_permissions: []

